Create azurerm_compute_virtualmachinescaleset.go
Azure/tflint-ruleset-avm pull request #64
Opened 2024-07-26 08:36 UTC by mbilalamjad

2024-07-26 08:50 UTC, matt-FFFFFF approved these changes
LGTM

2024-08-07 06:25 UTC, lonegunmanb requested changes
Hi @mbilalamjad almost LGTM but we need to remove all commented methods.

2024-08-07 06:25 UTC, lonegunmanb commented on waf/azurerm_compute_virtualmachinescaleset.go
> +/*
Would you please remove this commented method?

2024-08-07 06:25 UTC, lonegunmanb commented on waf/azurerm_service_plan.go
> +/*
Same here

2025-01-09 15:18 UTC, matt-FFFFFF approved these changes

2025-04-10 15:25 UTC, closed without merging